using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class ThirdPersonShooterController : MonoBehaviour
{
    Transform playerTransform;
    Animator animator;
    Transform cameraTransform;
    CharacterController characterController;

    public enum PlayerPosture
    {
        Crouch,
        Stand,
        Midair //æ»ç©º
    };
    [HideInInspector]
    public PlayerPosture playerPosture = PlayerPosture.Stand;

    float crouchThreshold = 0f;
    float standThreshold = 1f;
    float midairThreshold = 2.1f; // è¦å¤§äº2ï¼Œä¸ç„¶ä¼šåå¤æŠ–åŠ¨

    public enum LocomotionState
    {
        Idle,
        Walk,
        Run
    };
    [HideInInspector]
    public LocomotionState locomotionState = LocomotionState.Idle;

    public enum ArmState
    {
        Normal,
        Aim
    };
    [HideInInspector]
    public ArmState armState = ArmState.Normal;

    float crouchSpeed = 1.5f;
    float walkSpeed = 2.5f;
    float runSpeed = 5.5f;

    Vector2 moveInput;//æ¥æ”¶ç§»åŠ¨è¾“å…¥
    bool isRunning;
    bool isCrouch;
    bool isAiming;
    bool isJumping;

    // ä¿å­˜ç›¸å…³å‚æ•°çš„å“ˆå¸Œå€¼ï¼ˆæ€§èƒ½æ›´é«˜ï¼‰å¯¹åº”ä¿å­˜Animatorä¸­çš„Parameter
    int postureHash;
    int moveSpeedHash;
    int turnSpeedHash;
    int jumpSpeedHash;

    int feetTweenHash;

    Vector3 playerMovement = Vector3.zero;// ç©å®¶å®é™…ç§»åŠ¨çš„æ–¹å‘

    public float gravity = -9.8f; // é‡åŠ›

    float VerticalVelocity; //å‚ç›´æ–¹å‘é€Ÿåº¦

    //public float jumpVelocity = 5f; //å‘ä¸Šè·³è·ƒçš„é€Ÿåº¦

    public float maxJumpHigh = 1f; //ç©å®¶å¯è·³è·ƒçš„æœ€å¤§é«˜åº¦



    // å¯¹è·³è·ƒbugçš„è§£é™¤
    Vector3 lastVelOnGround;

    static readonly int CACHE_SIZE = 3; // ğŸŒŸ C#è¯­æ³•ï¼šreadonlyå…³é”®å­—ï¼Œä¸constçš„åŒºåˆ«åªåœ¨äºï¼Œconstä¸€å¼€å§‹å¿…é¡»èµ‹å€¼ã€‚å®ƒä»¬åŒæ ·æ˜¯èµ‹å€¼äº†ä¹‹åå°±ä¸èƒ½æ”¹äº†ã€‚
    Vector3[] velCache = new Vector3[CACHE_SIZE]; //ä¿å­˜ç¦»åœ°å‰3å¸§çš„ç§»åŠ¨é€Ÿåº¦
    int currentChacheIndex = 0;
    private Vector3 averageVel = Vector3.zero;

    float fallMultiplier = 1.5f; //ä¸‹é™çš„åŠ é€Ÿåº¦è¦æ¯”ä¸Šå‡çš„å¤šå¤šå°‘ã€‚

    // å¼ƒç”¨ccçš„isGrounded
    bool isGrounded;

    float groundCheckOffset = 0.5f; //å°„çº¿åç§»é‡

    // Start is called before the first frame update
    void Start()
    {
        playerTransform = transform; //æå‡è®¿é—®æ•ˆç‡
        animator = GetComponent<Animator>();
        characterController = GetComponent<CharacterController>();
        cameraTransform = Camera.main.transform;

        postureHash = Animator.StringToHash("ç©å®¶å§¿æ€");
        moveSpeedHash = Animator.StringToHash("ç§»åŠ¨é€Ÿåº¦");
        turnSpeedHash = Animator.StringToHash("è½¬å¼¯é€Ÿåº¦");
        jumpSpeedHash = Animator.StringToHash("å‚ç›´é€Ÿåº¦");
        feetTweenHash = Animator.StringToHash("å·¦å³è„š");
        Cursor.lockState = CursorLockMode.Locked;
    }

    // Update is called once per frame
    void Update()
    {
        CheckGround();
        CaculateGravity();
        Jump();
        CaculateInputDirection();
        SwitchPlayerStates();
        SetupAnimator();
    }

    #region è¾“å…¥ç›¸å…³
    public void GetMoveInput(InputAction.CallbackContext ctx)
    {
        moveInput = ctx.ReadValue<Vector2>();
    }

    public void GetRunInput(InputAction.CallbackContext ctx)
    {
        isRunning = ctx.ReadValueAsButton();
    }

    public void GetCrouchInput(InputAction.CallbackContext ctx)
    {
        isCrouch = ctx.ReadValueAsButton();
    }

    public void GetAimInput(InputAction.CallbackContext ctx)
    {
        isAiming = ctx.ReadValueAsButton();
    }

    public void GetJumpInput(InputAction.CallbackContext ctx)
    {
        isJumping = ctx.ReadValueAsButton();
    }
    #endregion
    void SwitchPlayerStates()
    {
        if(!isGrounded)
        {
            playerPosture = PlayerPosture.Midair;
        }
        else if(isCrouch) //è¦ä¸ºelse ifæ˜¯å› ä¸ºï¼Œå¦‚æœä¸åœ¨åœ°é¢ä¸èƒ½è¹²ã€‚
        {
            playerPosture = PlayerPosture.Crouch;
        }
        else
        {
            playerPosture = PlayerPosture.Stand;
        }
        if(moveInput.magnitude == 0) // å‘é‡çš„é•¿åº¦ï¼ŒåŠ(x,y)åˆ°(0,0)çš„è·ç¦»
        {
            locomotionState = LocomotionState.Idle;
        }
        else if(!isRunning)
        {
            locomotionState = LocomotionState.Walk;
        }
        else
        {
            locomotionState = LocomotionState.Run;
        }
        if(isAiming)
        {
            armState = ArmState.Aim;
        }
        else
        {
            armState = ArmState.Normal;
        }
    }

    void CheckGround()
    {
        if(Physics.SphereCast(playerTransform.position + (Vector3.up * groundCheckOffset), characterController.radius, Vector3.down, out RaycastHit hit, groundCheckOffset - characterController.radius + 2 * characterController.skinWidth))
        {
            isGrounded = true;
        }
        else
        {
            isGrounded = false;
        }
    }

    void Jump()
    {
        if(isGrounded && isJumping)
        {
            //VerticalVelocity = jumpVelocity;
            VerticalVelocity = Mathf.Sqrt(-2 * gravity * maxJumpHigh);
            float feetTween = Random.Range(-1f,1f);
            animator.SetFloat(feetTweenHash, feetTween);
        }
    }

    void CaculateGravity()
    {
        if(isGrounded) // isGroundedçš„æ£€æŸ¥å¿…é¡»è¦æ±‚è¦æœ‰å‘ä¸‹çš„åŠ é€Ÿåº¦ï¼Œä¸ç„¶ä¸ä¼šæ­£å¸¸å·¥ä½œï¼Œæ‰€ä»¥æˆ‘ä»¬è¦æŠŠè§’è‰²æŒ‰åœ¨åœ°ä¸Šï¼Œçœ‹ä¸‹é¢ä¸€è¡Œæ³¨é‡Šæ‰çš„æ˜¯åŸæ¥çš„
        {
            //VerticalVelocity = 0;
            //Debug.Log(characterController.isGrounded);
            VerticalVelocity = gravity * Time.deltaTime; // å…ˆåˆå§‹åŒ–ä¸º0
            return;
        }
        else //ä¸‹è½
        {
            if (VerticalVelocity <= 0)
            {
                VerticalVelocity += gravity * fallMultiplier * Time.deltaTime;
            }
            else
            {
                VerticalVelocity += gravity * Time.deltaTime; // é‡åŠ›åŠ é€Ÿåº¦å…¬å¼
            } 
        }
    }


    void CaculateInputDirection()
    {
        Vector3 camForwardProjection = new Vector3(cameraTransform.forward.x, 0, cameraTransform.forward.z).normalized;
        playerMovement = camForwardProjection * moveInput.y + cameraTransform.right * moveInput.x;
        playerMovement = playerTransform.InverseTransformVector(playerMovement);
    }

    void SetupAnimator()
    {
        if(playerPosture == PlayerPosture.Stand)
        {
            animator.SetFloat(postureHash, standThreshold, 0.1f, Time.deltaTime);
            switch(locomotionState)
            {
                case LocomotionState.Idle:
                    animator.SetFloat(moveSpeedHash, 0, 0.1f, Time.deltaTime);
                    break;
                case LocomotionState.Walk:
                    animator.SetFloat(moveSpeedHash, playerMovement.magnitude * walkSpeed, 0.1f, Time.deltaTime);
                    break;
                case LocomotionState.Run:
                    animator.SetFloat(moveSpeedHash, playerMovement.magnitude * runSpeed, 0.1f, Time.deltaTime);
                    break;
            }
        }
        else if(playerPosture == PlayerPosture.Crouch)
        {
            animator.SetFloat(postureHash, crouchThreshold, 0.1f, Time.deltaTime);
            switch(locomotionState)
            {
                case LocomotionState.Idle:
                    animator.SetFloat(moveSpeedHash, 0, 0.1f, Time.deltaTime);
                    break;
                default:
                    animator.SetFloat(moveSpeedHash, playerMovement.magnitude * crouchSpeed, 0.1f, Time.deltaTime);
                    break;
            }
        }
        else if(playerPosture == PlayerPosture.Midair)
        {
            // animator.SetFloat(postureHash, midairThreshold, 0.1f, Time.deltaTime);
            animator.SetFloat(postureHash, midairThreshold);
            // animator.SetFloat(jumpSpeedHash, VerticalVelocity, 0.1f, Time.deltaTime);
            animator.SetFloat(jumpSpeedHash, VerticalVelocity);
        }
        if(armState == ArmState.Normal)
        {
            float rad = Mathf.Atan2(playerMovement.x, playerMovement.z); // Atan2è¿”å›rad = arctan(å‚æ•°1ï¼Œå‚æ•°2) = aå¼§åº¦ = bè§’åº¦
            animator.SetFloat(turnSpeedHash, rad, 0.1f, Time.deltaTime); // ç”¨äº†CharacterControllerè½¬å‘ä¼šå¤±æ•ˆ
            // è½¬å‘é€Ÿåº¦åŠ å¿«
            playerTransform.Rotate(0, rad * 200 * Time.deltaTime, 0f);
        }
    }

    /// <summary>
    /// ç”¨åœ¨Updateé‡Œ,è¿”å›åŒ…æ‹¬å½“å‰å¸§çš„å‰ä¸‰å¸§çš„å¹³å‡é€Ÿåº¦ã€‚
    /// </summary>
    /// <param name="newVel">å½“å‰è¿™ä¸€å¸§çš„é€Ÿåº¦</param>
    /// <returns>èµ·è·³å‰å‰ä¸‰å¸§çš„é€Ÿåº¦</returns>
    Vector3 AverageVel(Vector3 newVel)
    {
        velCache[currentChacheIndex] = newVel;
        currentChacheIndex++;
        currentChacheIndex %= CACHE_SIZE; //å¯ä»¥ä¿è¯currentChacheIndexä¸€ç›´åœ¨0-2ã€‚é˜²æ­¢æº¢å‡º
        Vector3 average = Vector3.zero;
        foreach (Vector3 vel in velCache)
        {
            average += vel;
        }

        return average / CACHE_SIZE;
    }

    private void OnAnimatorMove()
    {
        // é‡åŠ›
        if(playerPosture != PlayerPosture.Midair)
        {
            Vector3 playerDeltaMovement = animator.deltaPosition;
            playerDeltaMovement.y = VerticalVelocity * Time.deltaTime; //è€å¸ˆè¿™é‡Œç”¨çš„æ˜¯=
            characterController.Move(playerDeltaMovement);
            // è®¡ç®—è·³è·ƒå‰å‰ä¸‰å¸§çš„é€Ÿåº¦ã€‚ï¼ˆè¿™ä¸ªä¸€å®šè¦æ”¾åœ¨éè·³è·ƒçŠ¶æ€è®¡ç®—å­˜å¥½ï¼Œä½ è·³åæ€ä¹ˆè·å–çš„åˆ°è·³å‰å‰ä¸‰å¸§é€Ÿåº¦å‘¢ï¼Ÿå°±é è¿™ä¸ªäº†ï¼‰
            averageVel = AverageVel(animator.velocity);
        }
        else
        {
            // é”™è¯¯æ–¹æ³•âŒ æ²¿ç”¨åœ°é¢é€Ÿåº¦ï¼Œæ¯”å¦‚ä½¿ç”¨æœ€åä¸€å¸§çš„é€Ÿåº¦ï¼ˆå®¹æ˜“å—å½±å“ï¼Œæ¯”å¦‚åœ°å½¢ï¼Œæˆ–è€…ä¸€äº›ç©å®¶å¥‡æ€ªçš„æ“ä½œï¼‰
            // æ­£ç¡®æ–¹æ³•âœ… æ²¿ç”¨åœ°é¢é€Ÿåº¦ï¼Œä½¿ç”¨å‰å‡ å¸§é€Ÿåº¦çš„å¹³å‡å€¼ï¼Œæ¥ä½œä¸ºè·³è·ƒçš„é€Ÿåº¦ï¼Œå¯ä»¥å°½é‡é¿å…å½±å“
            averageVel.y = VerticalVelocity;
            Vector3 playerDeltaMovement = averageVel * Time.deltaTime;
            playerDeltaMovement.y = VerticalVelocity * Time.deltaTime; //è€å¸ˆè¿™é‡Œç”¨çš„æ˜¯=
            characterController.Move(playerDeltaMovement);
        }
        
    }
}
